[package]
name = "getso"
version = "0.1.0"
authors = ["Andrei Bocan <zmaxor@gmail.com>"]

[dependencies]
clap = "*"
tokio = "*"
futures = "*"
native-tls = "*"
tokio-core = "*"
tokio-io = "*"
tokio-tls = "*"
openssl = "*"
ansi_term = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
